<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>Clientvenomrat</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Core">
      <HintPath>../../../../usr/share/dotnet/shared/Microsoft.NETCore.App/10.0.11/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Management" />
    <Reference Include="Microsoft.CSharp">
      <HintPath>../../../../usr/share/dotnet/shared/Microsoft.NETCore.App/10.0.11/Microsoft.CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.VisualBasic">
      <HintPath>../../../../usr/share/dotnet/shared/Microsoft.NETCore.App/10.0.11/Microsoft.VisualBasic.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>